### ISSUE TITLE
hi~

### ISSUE THREAD

**Issue by Ludwig1597** [Unique111/practices#1]
你好呀~今年大四，前段时间在准备考研，现在终于有点时间学习前端，以后想从事前端工程师。我不知道可不可以在这里留问题，，是第二次使用GitHub，我在b站看到了你的视频，但是好像已经很久不更新了，然后我想请教一下，就是vs code 和 网页同时分屏的情况下，如何都全屏呢，像b站你的视频里的那样，我的电脑是windows系统。如果按f11就只能单独全屏，而不能分屏，使用live server插件实时渲染。以及，我目前学习了JavaScript、jQuery、还将去学习一下vue，这是我一个月来的学习日志（https://blog.csdn.net/Ludwig1957?spm=1000.2115.3001.5343），但目前我觉得有点迷茫的时候，我能看懂你写的代码，和思路但是我好像自己却什么都写不出来，我应该怎么去练练手呢，我现在只能看着你们的视频去敲一遍，但是自己没有创意没有灵感。
希望哥哥/或是姐姐可以指点一下，谢谢！！

**Comment by Ludwig1597** [comment]
这是我的微信Ludwig1597，如果可以想认识一下~

**Comment by uniquemo** [comment]
@Ludwig1957 首先很感谢你的关注，后来比较忙，B站就没怎么更新了
学习前端的话，先把原生javascript学好；刚开始自己写不出来很正常，你可以先看懂别人的思路，然后自己去一点点实现；实现完以后可以对比下别人是怎么实现的，可以怎么优化等等，等写多了，你就有自己的思路了哈；
加油喔，实践很重要~

**Comment by Ludwig1597** [comment]
谢谢你！
